server:
  port: 8900
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8881/eureka/,http://localhost:8882/eureka/
spring:
  application:
    name: ribbon-consumer
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

