server:
  port: 8909
spring:
  application:
    name: trace-2
  sleuth:
    sampler:
      probability: 1
  rabbitmq:
    host: localhost
    port: 5672
    username: springcloud
    password: 123456789
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8881/eureka/
